/// Flutter icons TwicFont
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TwicFont
///      fonts:
///       - asset: fonts/TwicFont.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class TwicFont {
  TwicFont._();

  static const _kFontFam = 'TwicFont';

  static const IconData comment = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home_plain =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData empty_heart =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData plain_heart =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData library_icon =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData notification =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData private = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData search_2 =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData dessin = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData conversation_plain =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData search_3 =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData conversation =
      const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData hashtag = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData chat_empty =
      const IconData(0xf0e6, fontFamily: _kFontFam);
  static const IconData sliders = const IconData(0xf1de, fontFamily: _kFontFam);

  static const IconData group = const IconData(0xe813, fontFamily: _kFontFam);
}
